# Keep alphabetical and formatted correctly please
[versions]
#Main project
gradle-ktlint                   = "13.1.0"
kaml                            = "0.98.0"
kotest                          = "6.0.4"
kotlin                          = "2.2.20"
kotlinx-serialization-json      = "1.9.0"
kover                           = "0.9.3"
mockk                           = "1.14.6"
shadow-jar                      = "9.2.2"
testcontainers                  = "1.21.3"
# Gradle generator
wiremock                        = "3.13.1"

[libraries]
#Main project
kaml                            = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kotest-assertions-core          = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-table         = { module = "io.kotest:kotest-assertions-table", version.ref = "kotest" }
kotest-extensions               = { module = "io.kotest:kotest-extensions", version.ref = "kotest" }
kotest-framework-engine         = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotlin-stdlib                   = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlinx-serialization-json      = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
mockk                           = { module = "io.mockk:mockk", version.ref = "mockk" }
testcontainers                  = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
# Gradle generator
wiremock                        = { module = "org.wiremock:wiremock", version.ref = "wiremock" }

[bundles]
kotest                          = ["kotest-assertions-core" , "kotest-assertions-table", "kotest-framework-engine", "kotest-extensions"]

[plugins]
gradle-ktlint                   = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradle-ktlint" }
kotlin-jvm                      = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization     = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover                           = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
shadow-jar                      = { id = "com.gradleup.shadow", version.ref = "shadow-jar" }
kotest                          = { id = "io.kotest", version.ref = "kotest" }