# Keep alphabetical and formatted correctly please
[versions]
#Main project
gradle-ktlint                   = "14.0.1"
kaml                            = "0.104.0"
kotest                          = "6.1.2"
kotlin                          = "2.3.0"
kotlinx-serialization-json      = "1.10.0"
kover                           = "0.9.6"
mockk                           = "1.14.9"
shadow-jar                      = "9.1.0"
testcontainers                  = "2.0.3"
# Gradle generator
wiremock                        = "3.13.2"

[libraries]
#Main project
kaml                            = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kotest-assertions-core          = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-table         = { module = "io.kotest:kotest-assertions-table", version.ref = "kotest" }
kotest-runner-junit5            = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-stdlib                   = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlinx-serialization-json      = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
mockk                           = { module = "io.mockk:mockk", version.ref = "mockk" }
testcontainers                  = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
# Gradle generator
wiremock                        = { module = "org.wiremock:wiremock", version.ref = "wiremock" }

[bundles]
kotest                          = ["kotest-assertions-core" , "kotest-assertions-table", "kotest-runner-junit5"]

[plugins]
gradle-ktlint                   = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradle-ktlint" }
kotest-gradle-plugin            = { id = "io.kotest", version.ref = "kotest" }
kotlin-jvm                      = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization     = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover                           = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
shadow-jar                      = { id = "com.gradleup.shadow", version.ref = "shadow-jar" }