name: Build, Scan and Publish

on:
  push:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  call_test:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

#codeQl does not support kotlin 2.3 yet https://github.com/github/codeql/issues/20661
#  call_codeql_analysis:
#    name: CodeQL Analysis
#    needs: call_test
#    uses: ./.github/workflows/codeql.yml
#    permissions:
#      actions: read
#      contents: read
#      security-events: write

  call_publish:
    name: Build and Publish
    needs: [
      call_test,
#      call_codeql_analysis
    ]
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release' }}
    uses: ./.github/workflows/publish.yml
    with:
      event_name: ${{ github.event_name }}
      upload_url: ${{ github.event.release.upload_url }}
    permissions:
      contents: write
      packages: write
